services:
  frontend:
    image: 0xaress07/ecommerce-frontend:latest
    ports: 
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started
    command: /app/node_modules/.bin/vite --host 0.0.0

  backend:
    image: 0xaress07/ecommerce-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ecommerce-api-db
      - SPRING_DATASOURCE_USERNAME=taha
      - SPRING_DATASOURCE_PASSWORD=taha
      - FILE_UPLOAD_DIR=/opt/app/uploads
      - APP_JWT_SECRET=MzY0NTYxYmYyMWRmOTg1ZmY4ZDAwYzcyMzg4MzY1MjM4NzM3MzY1ZDM0Mzc2ZDI3NjY0YjU5NTA3OTdhNTA4NDcyMDIzNGNiNGE5ZTI4YzdmNGRlZWZiMjc0OTY0
      - APP_JWT_EXPIRATION_MILLISECONDS=86400000
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - uploads-data:/opt/app/uploads
  db:
    image: 0xaress07/ecommerce-db:latest
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce-api-db
      - MYSQL_USER=taha
      - MYSQL_PASSWORD=taha
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./dbdump.sql:/docker-entrypoint-initdb.d/dbdump.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "taha", "-ptaha"]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 30s
volumes:
  db-data:
  uploads-data: